### obtener todas las instituciones
GET http://localhost:3000/api/institucion

### POST (crear una nueva institucion)
# @name createInstitucion
POST http://localhost:3000/api/institucion
Content-Type: application/json

{
    "nombre": "Hogwarts",
    "ciudad": "Unknown",
    "pais": "Escocia"
}

### ID
@id = {{createInstitucion.response.body.data.id}}

###GET ONE (Obtener una institucion)
GET http://localhost:3000/api/institucion/{{id}}

###PUT (modificar una institucion)
PUT http://localhost:3000/api/institucion/{{id}}
Content-Type: application/json

{
    "nombre": "Hogwarts",
    "ciudad": "Unknown",
    "pais": "Scotland"
}


### POST-DELETE (crear una nueva institucion para luego ser borrada)
# @name createInstitucionToDelete
POST http://localhost:3000/api/institucion
Content-Type: application/json

{
    "nombre": "Beauxbatons",
    "ciudad": "Cannes",
    "pais": "Francia"
}

###Delete (Borrar una institucion)
@idToDelete = {{createInstitucionToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/institucion/{{idToDelete}}
###Notar que el idToDelete se utilizo solamente para borrar la institucion recien creada
###Para borrar la institucion correcta, se deberia usar un id especifico.
