### GET ALL
GET http://localhost:3000/api/patente/

### GET ALL patentes pendientes.
GET http://localhost:3000/api/patente/pending
### crear una nueva patente
POST http://localhost:3000/api/patente
Content-Type: application/json

{
    "fechaCreacion": "2024-11-02",
    "nombre": "Wingardium Leviosa V2.1",
    "descripcion": "Esto es una prueba",
    "instrucciones": "Esto es una prueba",
    "idMago": 2
    
}
###cosas
@idMago = 1
GET http://localhost:3000/api/patente/{{idMago}}
